import chowmein from "/Project-images/chowemin.jpeg";
import momo from "/Project-images/momo.jpeg";
import samosa from "/Project-images/samosa.jpeg";
import pizza from "/Project-images/pizza.jpeg";
import pasta from "/Project-images/pasta.jpeg";
import Friedrice from "/Project-images/Friedrice.jpeg";
import Biryani from "/Project-images/Biryani.jpeg";
import chickencurry from "/Project-images/chickencurry.jpg";

// Product data with more details
export const products = [
  {
    id: 1,
    name: "Vegetable Chowmein",
    image: chowmein,
    desc: "Stir-fried noodles with fresh vegetables and savory sauce",
    price: "40",
    category: "Noodles",
    rating: 4.5,
    cookTime: "15 min",
    spicyLevel: "Medium",
    isVeg: true,
    popular: true,
  },
  {
    id: 2,
    name: "Steamed Momos",
    image: momo,
    desc: "Delicate steamed dumplings filled with vegetables and spices",
    price: "60",
    category: "Appetizer",
    rating: 4.8,
    cookTime: "20 min",
    spicyLevel: "Mild",
    isVeg: true,
    popular: true,
  },
  {
    id: 3,
    name: "Crispy Samosa",
    image: samosa,
    desc: "Golden fried pastry filled with spiced potatoes and peas",
    price: "35",
    category: "Snack",
    rating: 4.3,
    cookTime: "25 min",
    spicyLevel: "Medium",
    isVeg: true,
    popular: false,
  },
  {
    id: 4,
    name: "Margherita Pizza",
    image: pizza,
    desc: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    price: "99",
    category: "Italian",
    rating: 4.6,
    cookTime: "20 min",
    spicyLevel: "Mild",
    isVeg: true,
    popular: true,
  },
  {
    id: 5,
    name: "Creamy Alfredo Pasta",
    image: pasta,
    desc: "Fettuccine pasta in rich parmesan cream sauce",
    price: "85",
    category: "Pasta",
    rating: 4.4,
    cookTime: "15 min",
    spicyLevel: "Mild",
    isVeg: true,
    popular: false,
  },
  {
    id: 6,
    name: "Vegetable Fried Rice",
    image: Friedrice,
    desc: "Fragrant rice stir-fried with mixed vegetables and soy sauce",
    price: "65",
    category: "Rice",
    rating: 4.2,
    cookTime: "18 min",
    spicyLevel: "Mild",
    isVeg: true,
    popular: true,
  },
  {
    id: 7,
    name: "Chicken Biryani",
    image: Biryani,
    desc: "Fragrant basmati rice with tender chicken and aromatic spices",
    price: "120",
    category: "Rice",
    rating: 4.7,
    cookTime: "30 min",
    spicyLevel: "Medium",
    isVeg: false,
    popular: true,
  },
  {
    id: 8,
    name: "Spicy Chicken Curry",
    image: chickencurry,
    desc: "Tender chicken in rich, spicy gravy with Indian spices",
    price: "110",
    category: "Curry",
    rating: 4.5,
    cookTime: "25 min",
    spicyLevel: "Hot",
    isVeg: false,
    popular: true,
  },
];
