const tipsData = [
  "For faster assistance with orders, please have your order ID ready.",
  "Try our new seasonal dishes for a fresh experience!",
  "Double-check your delivery address before placing an order.",
  "You can save favorite meals for quick re-ordering next time.",
  "Contact support via chat for quicker responses.",
  "Remember to check your spam folder if you don’t see our email reply.",
  "Our support team usually responds within 24 hours on weekdays.",
  "Be as detailed as possible in your message to help us serve you better.",
  "Did you know? You can also track your orders directly from your account page.",
  "A sharp knife is a safe knife. It requires less force, giving you more control and preventing slips.",
  "Read the entire recipe first. This is your mise en place for the mind and prevents stressful mistakes.",
  "Don't overcrowd the pan. Searing in batches ensures a beautiful, crispy crust instead of steaming your food.",
  "Let your meat rest after cooking. This allows the juices to redistribute, making it more tender and flavorful.",
  "Taste your food as you cook! Adjust seasoning gradually; you can always add more, but you can't take it out.",
  "Salt your pasta water generously. It should taste like the sea. This is your only chance to season the pasta itself.",
  "Embrace 'ugly' produce. Misshapen fruits and vegetables are just as nutritious and often less expensive.",
  "Your best health tool is a good chef's knife. Chopping fresh vegetables becomes a joy, not a chore.",
  "Roast your vegetables. High-heat roasting caramelizes their natural sugars, making them incredibly delicious.",
  "Build a 'flavor foundation' by sautéing onions, garlic, or celery in a little oil before adding other ingredients.",
  "Use acids to brighten a dish. A squeeze of lemon juice or a dash of vinegar at the end can make flavors pop.",
  "Cook with whole spices and toast them yourself. The flavor is infinitely more complex and aromatic than pre-ground.",
  "Keep your cutting boards clean. Use one for raw meats and another for produce to prevent cross-contamination.",
  "Learn to love your freezer. It's perfect for storing leftovers, batch-cooked meals, and overripe bananas for smoothies.",
  "Rinse canned beans. This can remove up to 40% of the added sodium.",
  "Hydrate with your food. Ingredients like cucumbers, celery, and watermelon contribute to your daily water intake.",
  "Eat the rainbow. Different colored vegetables offer different phytonutrients and antioxidants.",
  "Make your own salad dressing. It's simple, avoids preservatives, and tastes infinitely better than store-bought.",
  "Don't fear fat. Healthy fats like olive oil and avocado are essential for absorbing vitamins A, D, E, and K.",
  "Use herbs generously. Fresh herbs like parsley and cilantro are packed with nutrients and add fresh flavor without salt.",
  "Prep ingredients before you start cooking (mise en place). This makes the process calm, organized, and enjoyable.",
  "Choose whole grains. They provide more fiber, which aids digestion and helps you feel full longer.",
  "Don't boil your greens. Sauté or steam them quickly to preserve their color, texture, and nutrients.",
  "Embrace eggs. They are a fantastic, inexpensive source of high-quality protein and cook in minutes.",
  "Make a plan for leftovers. Turn last night's roast chicken into today's salad or soup to reduce food waste.",
  "Listen to your hunger cues. Eat when you're hungry and stop when you're comfortably full.",
  "Cook at home more often. You have complete control over the quality of ingredients and the amount of salt, sugar, and fat.",
  "Use Greek yogurt. It's a protein-packed substitute for sour cream, mayo, or even in baked goods.",
  "Store your herbs properly. Treat tender herbs like parsley like a bouquet—place them in a glass of water in the fridge.",
  "Massage your kale! Rubbing chopped kale with a little oil and salt breaks down its tough fibers, making it tender and sweeter.",
  "Keep your pantry stocked with healthy staples: canned tomatoes, beans, whole grains, oils, and vinegars.",
  "Drink a glass of water while you cook. It helps you stay hydrated and mindful before a meal.",
  "Add a Parmesan rind to simmering soups or stews. It adds a deep, savory, umami flavor as it melts.",
  "Don't peel everything. Many nutrients and a lot of fiber are stored in or just under the skin of vegetables like potatoes and carrots.",
  "Use a meat thermometer. It's the only surefire way to cook meat to a safe temperature without overcooking it.",
  "Make friends with lentils. They cook quickly, are full of protein and fiber, and are incredibly versatile.",
  "Bloom your spices. Adding spices to hot oil for 30 seconds before other liquids deepens and intensifies their flavor.",
  "Grate your own cheese. Pre-shredded cheese contains anti-caking agents and doesn't melt as well.",
  "Use citrus zest. The outer skin is packed with aromatic oils that add incredible flavor without acidity.",
  "Make your own spice blends. You can control the salt and avoid additives found in pre-made packets.",
  "Soak chopped onions in cold water for 10 minutes. This tames their sharp bite for use in raw salads and salsas.",
  "Cook once, eat twice. Grill an extra chicken breast or roast more vegetables to have ready for easy lunches.",
  "Use the right oil for the job. Use neutral oils like avocado for high-heat searing and extra virgin olive oil for finishing.",
  "Add a pinch of salt to your coffee grounds before brewing. It reduces bitterness and enhances the natural flavor.",
  "Store nuts and seeds in the freezer. Their high oil content means they can go rancid quickly at room temperature.",
  "Eat with all your senses. Appreciate the colors, smells, and textures on your plate—it's part of the nourishment.",
  "Clean as you go. A tidy workspace reduces stress and makes finishing the meal much more pleasant.",
  "Trust your instincts. Recipes are guides, not laws. Adjust them to your taste and dietary needs.",
  "Stay organized. A well-organized fridge reduces food waste—you'll actually see what you have to use.",
  "Invest in a good quality baking sheet. It heats evenly, preventing burnt cookies and unevenly roasted veggies.",
  "Use vegetable scraps to make stock. Keep a bag in your freezer for onion skins, carrot tops, and celery ends.",
  "Don't be afraid of salt. It is essential for enhancing flavor. Use it wisely throughout the cooking process, not just at the end.",
  "Share meals with others. The connection and joy of eating together are vital ingredients for well-being.",
  "The most important ingredient in any kitchen is curiosity. Have fun and don't be afraid to try new things!",
];

export default tipsData;
