export const partners = [
  {
    id: 1,
    name: "Spice Palace Restaurant",
    specialty: "Authentic Indian Cuisine",
    rating: 4.9,
    deliveryTime: "25-35 min",
    orders: 1250,
    image: "🍛",
    since: "2018",
    type: "Restaurant",
    deliverySetup: "In-house delivery team",
    challenge: "Low online visibility",
    tags: ["Fine Dining", "Halal Certified", "Family Business"],
  },
  {
    id: 2,
    name: "Mama's Italian Kitchen",
    specialty: "Traditional Italian Dishes",
    rating: 4.8,
    deliveryTime: "20-30 min",
    orders: 980,
    image: "🍝",
    since: "2015",
    type: "Restaurant",
    deliverySetup: "Dedicated delivery staff",
    challenge: "No website for online orders",
    tags: ["Wood Fire Pizza", "Wine Pairing", "Authentic"],
  },
  {
    id: 3,
    name: "Urban Bites Cafe",
    specialty: "Fusion & Continental",
    rating: 4.7,
    deliveryTime: "30-40 min",
    orders: 750,
    image: "☕",
    since: "2019",
    type: "Cafe & Bistro",
    deliverySetup: "Two delivery personnel",
    challenge: "Limited marketing budget",
    tags: ["Specialty Coffee", "Fresh Bakery", "Brunch"],
  },
  {
    id: 4,
    name: "Tandoori Nights",
    specialty: "North Indian Specialties",
    rating: 4.9,
    deliveryTime: "35-45 min",
    orders: 1100,
    image: "🔥",
    since: "2017",
    type: "Restaurant",
    deliverySetup: "Multiple delivery bikes",
    challenge: "Poor SEO ranking",
    tags: ["Tandoor Specials", "Catering", "Party Orders"],
  },
];

export const stats = [
  { number: "300+", label: "Partner Restaurants" },
  { number: "75k+", label: "Active Food Lovers" },
  { number: "150k+", label: "Monthly Orders" },
  { number: "95%", label: "Restaurant Retention Rate" },
];

export const problemsWeSolve = [
  {
    problem: "High Website Development Costs",
    solution: "Zero setup fee, commission-based model",
    icon: "💸",
  },
  {
    problem: "Poor Search Engine Visibility",
    solution: "Featured in our popular local food platform",
    icon: "🔍",
  },
  {
    problem: "Limited Marketing Budget",
    solution: "Access to our growing customer base",
    icon: "📈",
  },
  {
    problem: "No Online Ordering System",
    solution: "Complete ordering and payment solution",
    icon: "🛒",
  },
];
